name: sms_spam_detection
description: A Spam SMS Detection app
version: 1.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  another_telephony: ^0.4.1

  intl: ^0.17.0
  auto_size_text: ^3.0.0
  fluttertoast: ^8.0.8
  sqflite: ^2.0.0+4
  flutter_local_notifications:
    version: ^9.9.1
    platforms:
      linux:
        default_package: none
  contacts_service: ^0.6.3
  path: ^1.6.4
  json_annotation: ^4.0.1
  collection: ^1.14.11
  quiver: ^3.0.1
  shared_preferences: ^2.0.7
  percent_indicator: ^3.4.0
  visibility_detector: ^0.2.0
  permission_handler: ^8.1.6
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.2
  json_serializable: ^4.1.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato_regular.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono_regular.ttf
    - family: SpamSMS
      fonts:
        - asset: assets/fonts/spam_sms.ttf
